import { Roboto } from "next/font/google";
import "./globals.css";
// import { PatroliDateProvider } from "@/context/PatroliDateContext";

// components
// import Header from "@/components/header/Header";
// import Footer from "@/components/footer/Footer";
// import Map from "@/components/map/Map";

const roboto = Roboto({ subsets: ['latin'], 
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--font-roboto'
});

export const metadata = {
  title: "SIPP Karhutla",
  description: "Generated by create next app",
  icon: {
    icon: "/sipp-favicon.png",
    shortcut: "/sipp-favicon.png",
    apple: "/sipp-favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`} >
        {/* <Header /> */}
        {/* <Map /> */}
        {children}
        {/* <PatroliDateProvider></PatroliDateProvider> */}
        {/* <Footer /> */}
        
      </body>
    </html>
  );
}
